# ======================================================
# 拾い物で作ったものをとりあえず置いておきます
# ======================================================
ServerName localhost

LoadModule proxy_module           modules/mod_proxy.so
LoadModule proxy_http_module      modules/mod_proxy_http.so
LoadModule proxy_balancer_module  modules/mod_proxy_balancer.so
LoadModule lbmethod_byrequests_module modules/mod_lbmethod_byrequests.so
LoadModule slotmem_shm_module     modules/mod_slotmem_shm.so

Listen 8080

<VirtualHost *:8080>

    ProxyPreserveHost On

    # コンテキストパスを置き換え
    <Proxy "balancer://product-a">
        BalancerMember http://product-a-1:8080 
        BalancerMember http://product-a-2:8080
        ProxySet lbmethod=byrequests
    </Proxy>

    <Proxy "balancer://product-b">
        BalancerMember http://product-b-1:8080
        BalancerMember http://product-b-2:8080
        ProxySet lbmethod=byrequests
    </Proxy>

    <Proxy "balancer://product-c">
        BalancerMember http://product-c-1:8080
        BalancerMember http://product-c-2:8080
        ProxySet lbmethod=byrequests
    </Proxy>

    ProxyPass        /context-path-a/ balancer://product-a/context-path-a/
    ProxyPassReverse /context-path-a/ balancer://product-a/context-path-a/

    ProxyPass        /context-path-b/ balancer://product-b/context-path-b/
    ProxyPassReverse /context-path-b/ balancer://product-b/context-path-b/

    ProxyPass        /context-path-c/ balancer://product-c/context-path-c/
    ProxyPassReverse /context-path-c/ balancer://product-c/context-path-c/

</VirtualHost>